### ISSUE TITLE
error while building the package on installation

### ISSUE THREAD

**Issue by senis000** [cokelaer/spectrum#10]
Hi (newbie here)
I'm getting an error while trying to install with pip on windows 7, anaconda 2.4.0, python 3.5
pip install spectrum
the error seems to be happening during the building of the package since I get something similar if I try to build it myself with "python setup.py install"

Below the last output lines of pip install.

Building wheels for collected packages: spectrum
  Running setup.py bdist_wheel for spectrum
  Complete output from command C:\Python\Anaconda\python.exe -c "import setuptoo
ls;**file**='C:\Users\senis\AppData\Local\Temp\pip-build-4s5qgf6i\spectru
m\setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**,
 'exec'))" bdist_wheel -d C:\Users\senis\AppData\Local\Temp\tmptse64iuppip-wheel
-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\cpp
  copying src\cpp__init__.py -> build\lib.win-amd64-3.5\cpp
  creating build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\arma.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\burg.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\cholesky.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\cohere.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\correlation.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\correlog.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\covar.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\criteria.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\datasets.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\eigen.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\eigenfre.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\errors.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\levinson.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\linalg.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\linear_prediction.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\lpc.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\minvar.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\modcovar.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\mtm.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\periodogram.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\psd.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\toeplitz.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\tools.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\transfer.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\waveform.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\window.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum\yulewalker.py -> build\lib.win-amd64-3.5\spectrum
  copying src\spectrum__init__.py -> build\lib.win-amd64-3.5\spectrum
  running build_ext
  building 'spectrum.mydpss' extension
  error: [WinError 2] The system cannot find the file specified

---

  Failed building wheel for spectrum
Failed to build spectrum
Installing collected packages: spectrum
  Running setup.py install for spectrum
    Complete output from command C:\Python\Anaconda\python.exe -c "import setupt
ools, tokenize;**file**='C:\Users\senis\AppData\Local\Temp\pip-build-4s5qg
f6i\spectrum\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).
read().replace('\r\n', '\n'), **file**, 'exec'))" install --record C:\Users\seni
s\AppData\Local\Temp\pip-lr7725kt-record\install-record.txt --single-version-ext
ernally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    building 'spectrum.mydpss' extension
    error: [WinError 2] The system cannot find the file specified

```
----------------------------------------
```

Command "C:\Python\Anaconda\python.exe -c "import setuptools, tokenize;**file**=
'C:\Users\senis\AppData\Local\Temp\pip-build-4s5qgf6i\spectrum\setup.py'
;exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '
\n'), **file**, 'exec'))" install --record C:\Users\senis\AppData\Local\Temp\pip
-lr7725kt-record\install-record.txt --single-version-externally-managed --compil
e" failed with error code 1 in C:\Users\senis\AppData\Local\Temp\pip-build-4s5qg
f6i\spectrum

**Comment by carlkl** [comment]
see https://github.com/cokelaer/spectrum/issues/4#issuecomment-152581242

**Comment by lheald** [comment]
I'm having a similar error when trying to run a setup.py file for a program called flexible atomic code. I get the same file not found error like: 
running build
running build_py
copying python\__init__.py -> build\lib.win-amd64-2.7\pfac
copying python\const.py -> build\lib.win-amd64-2.7\pfac
copying python\config.py -> build\lib.win-amd64-2.7\pfac
copying python\table.py -> build\lib.win-amd64-2.7\pfac
copying python\atom.py -> build\lib.win-amd64-2.7\pfac
copying python\spm.py -> build\lib.win-amd64-2.7\pfac
running build_ext
building 'pfac.fac' extension
error: [Error 2] The system cannot find the file specified
make: *** [pfac] Error 1

I saw the comment linked above and created this file in the user folder but it didn't seem to help. Any thoughts?

**Comment by cokelaer** [comment]
This is not related to this package, is it ? Maybe you should rather send an issue on the homepage of the tool you are trying to install https://github.com/fnevgeny/fac

**Comment by lheald** [comment]
I believe it is a general python package problem. If I follow the instructions here https://wiki.python.org/moin/ExtensionTutorial
I get the same error of 
running build_ext
building 'examp' extension
error: [Error 2] The system cannot find the file specified

I'll try submitting to a more general forum. The above seemed related but maybe it's not. 

Thanks

**Comment by balajibecs20** [comment]
C:\python35\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'bugtrack_url'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing entry points to mod_wsgi.egg-info\entry_points.txt
writing top-level names to mod_wsgi.egg-info\top_level.txt
writing dependency_links to mod_wsgi.egg-info\dependency_links.txt
writing mod_wsgi.egg-info\PKG-INFO
reading manifest file 'mod_wsgi.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'docs\_build\html\_static\font\*'
writing manifest file 'mod_wsgi.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
copying src\server\apxs_config.py -> build\lib.win-amd64-3.5\mod_wsgi\server
running build_ext
building 'mod_wsgi.server.mod_wsgi' extension
error: [WinError 2] The system cannot find the file specified


me also same issue i am using xampp and windows 10
