### ISSUE TITLE
problem with dpss after update on scipy

### ISSUE THREAD

**Issue by senis000** [cokelaer/spectrum#18]
Spectrum was working perfectly in python 3.5 until I updated scipy to  0.18.1.
Now I get this error:

In[2]: import spectrum as spec
In [3]: spec.dpss(512,3,5)

TypeError                                 Traceback (most recent call last)
<ipython-input-7-88860ae3544e> in <module>()
----> 1 spec.dpss(512,3,5)

C:\Python\Anaconda\lib\site-packages\spectrum-0.6.1-py3.5-win-amd64.egg\spectrum
\mtm.py in dpss(N, NW, k)
    298
    299     # The values returned in lam are not exacly the same as in the follo
wing methods.
--> 300     acvs = _autocov(tapers.transpose(), debias=False) * N
    301     nidx = arange(N)
    302     W = float(NW)/N

C:\Python\Anaconda\lib\site-packages\spectrum-0.6.1-py3.5-win-amd64.egg\spectrum
\mtm.py in _autocov(s, **kwargs)
    386         s = remove_bias(s, axis)
    387     kwargs['debias'] = False
--> 388     return _crosscov(s, s, **kwargs)
    389
    390

C:\Python\Anaconda\lib\site-packages\spectrum-0.6.1-py3.5-win-amd64.egg\spectrum
\mtm.py in _crosscov(x, y, axis, all_lags, debias)
    422     slicing = [slice(d) for d in x.shape]
    423     slicing[axis] = slice(None,None,-1)
--> 424     sxy = _fftconvolve(x, y[tuple(slicing)], axis=axis, mode='full')
    425     N = x.shape[axis]
    426     sxy /= N

C:\Python\Anaconda\lib\site-packages\spectrum-0.6.1-py3.5-win-amd64.egg\spectrum
\mtm.py in _fftconvolve(in1, in2, mode, axis)
    506         ret = ifftn(IN1)[fslice].copy()
    507     else:
--> 508         IN1 = fft(in1,fsize,axis=axis)
    509         IN1 *= fft(in2,fsize,axis=axis)
    510         ret = ifft(IN1,axis=axis)[fslice].copy()

C:\Python\Anaconda\lib\site-packages\scipy\fftpack\basic.py in fft(x, n, axis, o
verwrite_x)
    265         n = tmp.shape[axis]
    266     elif n != tmp.shape[axis]:
--> 267         tmp, copy_made = _fix_shape(tmp,n,axis)
    268         overwrite_x = overwrite_x or copy_made
    269

C:\Python\Anaconda\lib\site-packages\scipy\fftpack\basic.py in _fix_shape(x, n,
axis)
    151         index[axis] = slice(0,s[axis])
    152         s[axis] = n
--> 153         z = zeros(s,x.dtype.char)
    154         z[index] = x
    155         return z, True

TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by senis000** [comment]
Hi, the problem was with the scipy package after a problem updating with conda 
(see https://github.com/conda/conda/issues for a solution)

**Comment by cokelaer** [comment]
thanks for the report.

**Comment by dhruv13J** [comment]
Hi,
I tried running the following on a python2 jupyter notebook:

    from spectrum import *
    
    N = 512
    [w, eigens] = dpss(N, 2.5, 4)

I get precisely the error reported by @senis000 (TypeError: 'numpy.float64' object cannot be interpreted as an integer; same stack trace too) which is strange because I don't see where numpy would have a problem. I don't use anaconda and installed all my packages using pip.

**Comment by dhruv13J** [comment]
Hi,
Uninstalling the package using pip and Installing the latest clone from source fixed the issue for me. I'm sorry, I should have really done that before. I hope this helps anyone else who has the same problem. 
@cokelaer: Out of curiosity, was there anything different between versions 0.6.2 (which pip installed for me) and 0.6.3 (the latest) which fixes this? And it would be a good idea to close the issue now.
BTW, a big thank you for developing this!

**Comment by anielsen001** [comment]
What's happened is that numpy no longer allows floating point numbers to be used as indices, they have to be cast to integers first. I discovered this in a part of dpss and @cokelaer fixed the remaining indexing changes.

**Comment by NEGU93** [comment]
I have run:
`pip install --upgrade --no-deps --force-reinstall`
But still have the same problem. I have the version 0.6.2.
Does somebody know the reason?

**Comment by cokelaer** [comment]
This was most probably fixed all across the code in version 0.6.4 after reports from #21 and this report.
