### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by rene-aguirre** [cokelaer/spectrum#19]
Most python libraries are relatively permissive in terms of licensing (example, BSD or MIT like).

This includes Numpy and Scipy, which IMO fall in a similar domain as this project (https://www.scipy.org/scipylib/license.html, https://docs.scipy.org/doc/numpy-1.10.0/license.html)

Just wondering why did you choose LGPL under provided a more permissive Python library environment?

**Comment by cokelaer** [comment]
Hi, no specific reasons. I'm moving my code to BSD those days and will switch to BSD3 for spectrum as well in the close future.

**Comment by rene-aguirre** [comment]
Thanks @cokelaer that'd be awesome!

**Comment by cokelaer** [comment]
BSD3 now with a license file included and updated setup file
