### ISSUE TITLE
No output at Jupyter Notebook

### ISSUE THREAD

**Issue by jmarcoscosta** [cokelaer/spectrum#25]
from spectrum.window import Window
h = Window(64, name='hamming')
h.plot_time_freq()

I just tried to run the code above at Jupyter notebook code cell. No problem was reported, but no outputs either. 
EDIT: I had to use '%matplotlib inline' for the plotting to be shown.

**Comment by cokelaer** [comment]
This is a known jupyter feature. Glad you found the solution. Closing the issue since this is not related to spectrum.
