### ISSUE TITLE
spectrogram implementation

### ISSUE THREAD

**Issue by cokelaer** [cokelaer/spectrum#40]
need to check the x and y axis

**Comment by alandastudillo** [comment]
Hello. There is a problem with the visualization of spectrogram in the spectrogram function, specifically in the function plot at the line:
**yy = [int(this) for this in np.array(ypos) / YMAX * p.sampling]**
I thing that the correct line should be with a division by two regarding the fft rule of the half sampling frequency:
**yy = [int(this) for this in np.array(ypos) / YMAX * p.sampling/2]**
Please check this and text me if I am wrong. I am new on github so sorry for not to be more practical.
Thank you for your work. Regards
