### ISSUE TITLE
Authorship on JOSS paper

### ISSUE THREAD

**Issue by cokelaer** [cokelaer/spectrum#41]
@juhasch @anielsen001 @carlkl 
I've submitted a paper to [JOSS](https://github.com/openjournals/) describing the Spectrum package. It's currently under review, and you can read the review and response at the [link.](https://github.com/openjournals/joss-reviews/issues/348).

Please let me know by 16 Oct if you'd like to be listed as co-authors on the paper, in which case please send me your current affiliation and ORCID.

**Comment by juhasch** [comment]
Hi @cokelaer,
not sure if my not so large contribution qualifies me as co-author. If you think that's appropriate:
http://orcid.org/0000-0002-9457-1220

**Comment by cokelaer** [comment]
@juhasch we'll add you to the author list. thanks for your contributions

**Comment by stringhamc** [comment]
Hi @cokelaer, I appreciate the offer. At this point there is no need to add me as an author as my only contribution is implementing a previously documented function. But I'll check out the paper. Thanks again!

**Comment by cokelaer** [comment]
@juhasch and @stringhamc  so I will proceed with the finalisation of the paper. 
Just to be fair with open source contributions, your commits were useful and if you want you can just update this file in the spectrum repo: 

https://github.com/cokelaer/spectrum/blob/master/doc/joss/paper.md

adding your name/affiliation (if relevant) and ORCID.  If you could do so before the end of the week, that would be great so that I can finalise the JOSS submission. 
best

**Comment by cokelaer** [comment]
FYI @juhasch @stringhamc reading back your messages in more details, I have included Juergen only in the JOSS meta data information in the author list.
