### ISSUE TITLE
Syntax error in taylor window

### ISSUE THREAD

**Issue by Aikhjarto** [cokelaer/spectrum#45]
Line 1189 in window.py contains "np.sum(...)" which should be "sum(...)" since numpy is not imported as np.

**Comment by Aikhjarto** [comment]
Ah, I see that this was already fixed with 4b9cf4f08f090cdc36fd6cae3f4c87b5f5311e45
However, this fix is not included in pip's repo.

**Comment by cokelaer** [comment]
I've just uploaded a new version on pypi. That should fix this issue; Thanks for reporting this.
