### ISSUE TITLE
Multi-tapering example not working

### ISSUE THREAD

**Issue by Strong-Curious** [cokelaer/spectrum#48]
I'm trying to test the multi-taper calculation with the example:

```
from spectrum import *

data = data_cosine(N=2048, A=0.1, sampling=1024, freq=200)
# If you already have the DPSS windows
[tapers, eigen] = dpss(2048, 2.5, 4)
res = pmtm(data, e=tapers, v=eigen, show=False)
```

But I'm getting the error:

`ValueError: operands could not be broadcast together with shapes (4,) (2048,) `

I'm using latest Spectrum with anaconda on Windows 64-bit.

**Comment by xaratustrah** [comment]
I can reproduce the error on macos 64, anaconda python 3.6.5.

**Comment by cokelaer** [comment]
@xaratustrah thanks for the answer. This was indeed a typo in the snippet provided.
