### ISSUE TITLE
pyule does not return the correct frequencies.

### ISSUE THREAD

**Issue by wanglongqi** [cokelaer/spectrum#5]
pyule does not return the correct scaled frequencies as is demonstrated below:

	In [1]: import spectrum as sp

	In [2]: import numpy as np

	In [3]: sig = np.random.random((100,1))

	In [4]: s = sp.pyule(sig, 8, sampling = 64)

	In [5]: s.run()

	In [6]: 1/s.df
	Out[6]: 100.0

	In [7]: s.sampling
	Out[7]: 64

	In [8]: s.frequencies()[-1]
	Out[8]: 0.5

**Comment by cokelaer** [comment]
should work now from the github repo
