### ISSUE TITLE
scipy fftn produces warning that numpy fftn does not

### ISSUE THREAD

**Issue by anielsen001** [cokelaer/spectrum#51]
When working on addressing the deprecation warning announced in #49 , I found that the scipy.fftpack.fftn produces a different warning:

```
import numpy as np
from scipy.fftpack import fftn
a = np.random.random([16,16])
fftn(a, [32,32])      
```                                                              
/home/apn/proj/spectrum/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-x86_64.egg/scipy/fftpack/basic.py:160: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  z[index] = x

If you use the numpy version of fftn, this warning goes away, and the answers are the same:

`np.allclose(np.fft.fftn(a,[32,32])  , fftn(a, [32,32]))`

is True

I'm not sure if there's a reason to choose one of the `fftn` over another, but the warning appears to come from scipy and could be removed by switching to the numpy version.

I'm suing scipy 1.1.0, numpy 1.15.2 and python 3.6.5

**Comment by cokelaer** [comment]
no more warnings with current version of python (3.7.3) and latest scipy/numpy version.
closing for now
