### ISSUE TITLE
Odd ylabel position in plot_time_freq 

### ISSUE THREAD

**Issue by Aikhjarto** [cokelaer/spectrum#52]
Using plot_time_freq of a Window. The ylabel of the spectrum is plotted over the time domain plot.
Possible solution: add some space between time domain and frequency domain plot.

MWE:
```
import spectrum
wind=spectrum.Window(128,'hanning')
wind.plot_time_freq()
```
Result
![window_hanning](https://user-images.githubusercontent.com/3519989/48560253-b2d50c00-e8ed-11e8-99e0-d88765f45566.png)

**Comment by cokelaer** [comment]
thanks for reporting this issue. I am not aware of a general solution for this.
I have added a call to tight_layout() in the function , which should fix the issue under linux. 
Another solution is to move the label to the right or to call each plot individually using:
plot_window() and plot_frequencies().

**Comment by cokelaer** [comment]
Fixed by placing the label to the right of the image. previous behaviour (ylabel to the left) is still 
possible using yaxis_label_position argument.
