### ISSUE TITLE
minor interpretation pmtm out data issue

### ISSUE THREAD

**Issue by jessecob13** [cokelaer/spectrum#53]
I am unable to understand the output of the pmtm. I do not want to plot directly using the *show = true* so I would like to take the Sk and weight variables and combine them appropriately. They come out different shapes, so I am assuming a transpose will fix this issue. For example, is n=1024, k=4,
then I will:

1) element by element multiply the Sk matrix by the transpose(weight) matrix.
2) then add them to get the correct tapered and weighted FFT.
3) compute spectrum or whatever is desired.

Thanks, sorry for not posting an actual issue.

**Comment by cokelaer** [comment]
You should look at the MultiTapering class in the spectrum.mtm module. 
There we call the pmtm function and use the Sk complex signal. Depending on the method , you may need to transpose the data or not. By default, you should use the tranposed signal indeed. Then, indeed you need to multiply by the weights. In step 2, we actually take the mean. Please see the code source for more details. As for step 3, a 10 log10 or 20 log10 plot should do it.
