### ISSUE TITLE
Real datatype, appending last value not always required

### ISSUE THREAD

**Issue by alfredo-f** [cokelaer/spectrum#54]
TODO comment left at burg.py:145 was right
`# TODO: check the last value is correct or required ?`
in case `int(self.NFFT//2)` is odd, appending last value is not required because the length is already odd.

For example,
`self.NFFT = 1189` —> `int(self.NFFT//2) = **594**` —> append... is **needed** to get length 595
`self.NFFT = 1186` —> `int(self.NFFT//2) = **593**` —> append... is **not needed**, length already odd

In attach, explanation from MATLAB implementation help
![screen shot 2018-11-28 at 08 44 11](https://user-images.githubusercontent.com/22865959/49136734-d84d1700-f2ea-11e8-9507-515b1a48a310.jpg)

**Comment by cokelaer** [comment]
Thanks for reporting this. Indeed in test, 8//2 or 9//2 is identical (4) but for larger values this is not the case. I will need to correct this in a few other places indeed. will be incorporated in the next release.

**Comment by cokelaer** [comment]
* For NFFT = 1189, the data is odd and therefore the final PSD length is (1189+1)/2 that is 595.
* For NFFT = 1186, the data is even and PXX is indeed 1186/2+1 = 594

This had implication in various places in the code for real data case where conversion between onesided/twosided/centerdc was not handling the last value correctly. Hopefully this is now corrected all over the place and should be available in version 0.7.5
