### ISSUE TITLE
conda-forge

### ISSUE THREAD

**Issue by Aikhjarto** [cokelaer/spectrum#55]
README.rst says to use `conda config --add channels conda-forge`. However, on conda>4.1 this leads to a channel order where conda-forge has a higher priority than the defaults channel. Documentation is here: https://conda.io/docs/user-guide/tasks/manage-channels.html
This will lead to undesirabley switching ALL packages (not only spectrum) to conda-forge with the next `conda update`.
Maybe you can change it to `conda config --append channels conda-forge`.

**Comment by cokelaer** [comment]
I have now changed the doc and readme files
