### ISSUE TITLE
Spectrum on 2D spatial data?

### ISSUE THREAD

**Issue by patrickcgray** [cokelaer/spectrum#65]
Is there any documentation or examples of how to use spectrum on 2D data to take a power spectrum of an image? Then I'm planning to azimuthally average that 2D power spectrum to get my 1D power spectrum.

**Comment by sabraha2** [comment]
Are you looking for something like this? 
https://fairyonice.github.io/Frequency-analysis-of-images-from-scratch.html

**Comment by patrickcgray** [comment]
That's a good overview, thanks for the link! I ended up using this xarray based isotropic power spectrum function: https://xrft.readthedocs.io/en/latest/MITgcm_example.html#Power-spectrum
