### ISSUE TITLE
What is the output of pmtm?

### ISSUE THREAD

**Issue by patrickcgray** [cokelaer/spectrum#68]
I'm unclear what exactly the [pmtm](http://thomas-cokelaer.info/software/spectrum/html/user/ref_mtm.html?highlight=pmtm#spectrum.mtm.pmtm) function is outputting? It returns three np.arrays and the documentation doesn't say what it returns. 

I'm not sure what to do to those output arrays to get the actual multitapered output and produce a plot similar to what is returned from the `show=True` parameter. Do I need to average one of the arrays in the output? This doesn't seem to match the plot. Any advice or examples would be much appreciated!

**Comment by patrickcgray** [comment]
Okay I was able to dig into the code a bit and make some more sense of it. I've now written a  function that I think is correctly taking the output of pmtm and returning the power and frequency at each bin. I've also included an argument dx_of_pix because I'm using this for satellite imagery and that is the resolution of each pixel so that the x axis is actually the accurate wavenumber at each bin. Does this look correct?

```
def pmtm_spec_and_freqs(input_samples, dx_of_pix, NW=4, show=False):
  Sk_complex, weights, eigenvalues = pmtm(input_samples, NW=NW, method='adapt')

  Sk = abs(Sk_complex)**2
  Sk = np.mean(Sk.T * weights, axis=1)

  # calculate frequency bins based on f = x / NFFT * (sampling rate in Hz or 1/dx of pixels))
  NFFT = max(256, 2**nextpow2(len(input_samples)))
  bins = np.linspace(1,NFFT,NFFT)
  f = bins / NFFT * (1/dx_of_pix)
  # then we need to adjust them by the diff of the transect count and NFFT/2
  freq = f[:int(Sk.shape[0]/2)] * 1/(input_samples.shape[0]/int(Sk.shape[0]/2))
  # only take the first half of the values because the second half is the negative set
  real_var = Sk[:int(Sk.shape[0]/2)]

  if show:
    # plot the area that is viable based on Ana's quoted numbers
    plt.axvline(1/(700/8), ls='--', color='green')
    plt.axvline(1/(2*7), ls='--', color='green')

    plt.plot(freq, real_var)
    plt.xscale('log')
    plt.yscale('log')

  return(real_var, freq)
```

**Comment by cokelaer** [comment]
Thanks for proposing this solution. Actually, it is available in the Multitapering class from the pmtm module. The plot function in pmtm is indeed not correct. I have kept it to help debugging but Multitapring should be used. It is a wrapper around the pmtm function + better plotting that implemented what you have written in your comment but using the same function as for all other spectral analysis tools available in this library. I will close this issue since I believe it is now documented in more details

**Comment by mnky9800n** [comment]
Should you be calculating

```
abs(sk_complex)**2
```

or 

```
abs(sk_complex * sk_complex.conj())
```
