### ISSUE TITLE
method used in spectrum.ma ?

### ISSUE THREAD

**Issue by DaboudetClaire** [cokelaer/spectrum#69]
Hi :) I would like to use your MA parameters estimations. But i don't find the name of the used method. Is it th Durbin's method ? (Some similarities) 

Thanks,

Claire

**Comment by cokelaer** [comment]
Dear Claire, I believe you are looking for the function ma() available in the arma module.
This is a wrapper of the Yule Walker algorithm from the module spectrum.yulewalker.aryule.
The equations are solved with a levinson-durbin recursion as far a I remember.
