### ISSUE TITLE
pip install version 0.9

### ISSUE THREAD

**Issue by roitnedurp** [cokelaer/spectrum#80]
Problem
=======
The actual version is 0.8.1, but installing spectrum with pip, without version specification, get version 0.9. 

[verbatim begin]
pip install spectrum
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting spectrum
  Using cached https://www.piwheels.org/simple/spectrum/spectrum-0.9-py3-none-any.whl (82 kB)
Requirement already satisfied: matplotlib in ./.local/lib/python3.9/site-packages (from spectrum) (3.6.3)
Requirement already satisfied: numpy in ./.local/lib/python3.9/site-packages (from spectrum) (1.21.4)
Requirement already satisfied: scipy in ./.local/lib/python3.9/site-packages (from spectrum) (1.10.1)
Requirement already satisfied: contourpy>=1.0.1 in ./.local/lib/python3.9/site-packages (from matplotlib->spectrum) (1.0.6)
Requirement already satisfied: cycler>=0.10 in ./.local/lib/python3.9/site-packages (from matplotlib->spectrum) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in ./.local/lib/python3.9/site-packages (from matplotlib->spectrum) (4.28.4)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.local/lib/python3.9/site-packages (from matplotlib->spectrum) (1.3.2)
Requirement already satisfied: packaging>=20.0 in ./.local/lib/python3.9/site-packages (from matplotlib->spectrum) (21.3)
Requirement already satisfied: pillow>=6.2.0 in ./.local/lib/python3.9/site-packages (from matplotlib->spectrum) (8.4.0)
Requirement already satisfied: pyparsing>=2.2.1 in ./.local/lib/python3.9/site-packages (from matplotlib->spectrum) (3.0.6)
Requirement already satisfied: python-dateutil>=2.7 in ./.local/lib/python3.9/site-packages (from matplotlib->spectrum) (2.8.2)
Requirement already satisfied: six>=1.5 in ./.local/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib->spectrum) (1.16.0)
Installing collected packages: spectrum
Successfully installed spectrum-0.9
[verbatim end]

Opening ipython and importing  the installed version 0.9 of spectrum return  errors.

Errors
=====

[verbatim begin]
In [1]: import spectrum
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-09110c0fcd79> in <module>
----> 1 import spectrum

~/.local/lib/python3.9/site-packages/spectrum/__init__.py in <module>
      4 default_NPSD = 4096
      5 
----> 6 import arma
      7 import burg
      8 import cholesky

ModuleNotFoundError: No module named 'arma'

[verbatim end]

Roundabout way
==============

To install without errors the version must be specified:

[verbatim begin]

pip install spectrum==0.8.1

[verbatim end]

**Comment by cokelaer** [comment]
dear @roitnedurp 

thanks for reporting this issue. I am quite surprised since I have not released any version 0.9.0  The current version is indeed 0.8.1 both in the github and on pypi website (used when you type pip install commands). Have you maybe clone and install the package from source (and setting the version to 0.9.0 at some point) ? I see that it downloads from piwheel website, that I did not know. Yet, only v0.8.1 is available there as well. So, I do not know how come there is that specific version that interfers. sorry

**Comment by cokelaer** [comment]
release 0.9.0 now on pypi. still do not know what happened in your case. closing. no solution. sorry
