### ISSUE TITLE
Deprecated use of pkg_resources

### ISSUE THREAD

**Issue by mh105** [cokelaer/spectrum#81]
**1. Describe the bug**
I noticed that spectrum is still using pkg_resources to manage file paths. After 3.10 there is now a warning message for deprecated API.

**2. To Reproduce**
- OS: any
- Python version. >3.10
- Version of spectrum: 0.8.1

Just need to import spectrum and this warning message is elicited: 

```
DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources
```

**3.Expected behavior**
We should switch to use `importlib.resources` and `importlib.metadata` for the same functionalities.

**Comment by cokelaer** [comment]
@mh105 probably fixed in version 0.9.0 now on pypi
