### ISSUE TITLE
Numpy product deprecated  _autocov function in mtm.py needs updated

### ISSUE THREAD

**Issue by WyattSP** [cokelaer/spectrum#84]
Error:
For spectrum.pmtm error in acvs = _autocov(tapers.transpose(), debias=False) * N:
ImportError: cannot import name 'product' from 'numpy'

To Reproduce:
To reproduce error run spectrum.pmtm with Numpy version 2.0.0

Fix: 
Numpy import in mtm.py for _autocov function needs to be changed to:
from numpy import prod as product

**Comment by cokelaer** [comment]
@WyattSP probably fixed in version 0.9.0 now on pypi
