### ISSUE TITLE
Strong line in the middle of MTM spectrum

### ISSUE THREAD

**Issue by xaratustrah** [cokelaer/spectrum#9]
Hi,
when using MTM, I get a strong component at zero, which looks like an artifact, no matter what the time bandwidth product or the number of Slepians are. For comparison, I send the pure FFT (numpy) compared to MTM (spectrum 0.6.1) of an example data set. This happens of course with other data as well.

Any ideas are welcome!
Cheers!

**UPDATE:**

sorry it seems that I have been feeding the `pmtm` abs value of a complex (IQ) signal, which is the cause of the problem. Now I have to check how to go complex.

:-)

**Comment by xaratustrah** [comment]
`pmtm` expects real valued ndarray. I was using a complex64 array which caused the problem. So in principle this is not an issue of spectrum 0.6.1. sorry for inconvenience.

**Comment by cokelaer** [comment]
Thanks for closing the issue with an explanation.
